CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL
);

ALTER TABLE servers
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);

ALTER TABLE deployments
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
